---
language: python
rvm:
  - 2.3
sudo: required

services:
  - docker

before_install: "./test/scripts/before-install.sh"
install: "./test/scripts/install.sh"
script: "./test/scripts/test-role.sh"

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
