---

allow_duplicates: no

galaxy_info:
  author: Marco Ferrari
  description: Ansible role to install Oracle SQL Developer
  license: "license (Apache 2.0)"
  min_ansible_version: 2.2
  platforms:
    - name: Ubuntu
      versions:
        - xenial
  galaxy_tags:
    - database
    - development
