---
- name: download and install essential/basic packages and pre-requisites
  apt: name={{ item }} state=present
  with_items: "{{ basic }}"

- name: add keys for repos
  apt_key: url="{{ item.value.repo_key}}"
  when: item.value.repo_key is defined
  with_dict: "{{ mains }}"

- name: setup repositries
  apt_repository: repo={{ item.value.repo }} state=present
  when: item.value.repo is defined
  with_dict: "{{ mains }}"

- name: downloading and installing packages
  apt: name={{ item.key }} state=present
  with_dict: "{{ mains }}"

- name: Download packages files
  get_url: url="{{ item.value.url }}" dest="{{ item.value.path }}" mode=0644
  with_dict: "{{ packages }}"

- name: install packages
  apt: deb="{{ item.value.path }}"
  with_dict: "{{ packages }}"
