---
- name: enable 32bit arch support
  lineinfile: dest=/var/lib/dpkg/arch line="i386"

- name: create downloads directory
  file: path="{{ downloads_directory}}" state=directory mode=0644

- name: download and install essential/basic packages and pre-requisites
  apt: name={{ item }} state=present autoclean=yes autoremove=y cache_valid_time=86400
  with_items: "{{ basic }}"

- name: add keys for repos
  apt_key: url="{{ item.value.repo_key}}"
  when: item.value.repo_key is defined
  with_dict: "{{ mains }}"

- name: setup repositries
  apt_repository: repo={{ item.value.repo }} state=present
  when: item.value.repo is defined
  with_dict: "{{ mains }}"

- name: downloading and installing packages
  apt: name={{ item.key }} state=present cache_valid_time=86400
  with_dict: "{{ mains }}"

- name: Download packages files
  get_url: url="{{ item.value.url }}" dest="{{ item.value.path }}" mode=0644
  with_dict: "{{ packages }}"

- name: install packages
  apt: deb="{{ item.value.path }}"
  with_dict: "{{ packages }}"

- name: Download archived packages files
  get_url: url="{{ item.value.url }}" dest="{{ item.value.path }}" mode=0644
  with_dict: "{{ archives }}"

- name: unarchiving packages
  unarchive: src="{{ downloads_directory }}/{{ item.key }}.tar.gz" dest=/opt/ remote_src=yes mode=0755
  with_dict: "{{ archives }}"
