---
- name: enable 32bit arch support
  lineinfile: dest=/var/lib/dpkg/arch line="i386"

- name: create downloads directory
  file: path="{{ downloads_directory}}" state=directory mode=0644

- name: apt update
  apt: update_cache=yes autoclean=yes autoremove=y cache_valid_time=0

- name: download and install essential packages and pre-requisites
  apt: name={{ item }} state=present  cache_valid_time=86400
  with_items:
    - apt-transport-https
    - ca-certificates
    - software-properties-common
    - curl
    - build-essential
    - python-pip
    - python-virtualenv
    - net-tools
    - tar
    - openjdk-8-jdk

- name: add keys for repos
  apt_key: url="{{ item }}"
  with_items:
    - https://dl-ssl.google.com/linux/linux_signing_key.pub
    - https://download.docker.com/linux/ubuntu/gpg

- name: setup repositries
  apt_repository: repo={{ item }} state=present
  with_items:
    - ppa:notepadqq-team/notepadqq
    - ppa:dreibh/ppa
    - ppa:webupd8team/atom
    - deb http://dl.google.com/linux/chrome/deb/ stable main
    - deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable


- name: Download packages files
  get_url: url="{{ item.value.url }}" dest="{{ item.value.path }}" mode=0644
  with_dict: "{{ packages }}"

- name: install packages
  apt: deb="{{ item.value.path }}"
  with_dict: "{{ packages }}"

- name: Download archived packages files
  get_url: url="{{ item.value.url }}" dest="{{ item.value.path }}" mode=0644
  with_dict: "{{ archives }}"

- name: unarchiving
  unarchive: src="{{ downloads_directory }}/{{ item.key }}.tar.gz" dest=/opt/ remote_src=yes mode=0755
  with_dict: "{{ archives }}"

- name: running installers silently
  shell: "{{ item }}"
  with_items:
    - sh /opt/jprofiler*/bin/jprofiler
    - sh 

- name: install some packages
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=86400
  with_items:
    - atom
    - google-chrome-stable
    - vagrant
    - docker-ce
    - virtualbox
    - filezilla
    - notepadqq
    - vlc
    - xpad
    - wireshark
    - putty
