---

- name: enable 32bit arch support
  lineinfile: dest=/var/lib/dpkg/arch line="i386" create=yes
  sudo: yes

- name: create downloads directory
  file:
    path: "{{ downloads_directory}}"
    state: directory
    mode: 0777

- name: download and install essential packages and pre-requisites
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=86400
  with_items:
    - apt-transport-https
    - ca-certificates
    - software-properties-common
    - curl
    - build-essential
    - python-pip
    - python-virtualenv
    - net-tools
    - tar


- name: add private_keys for repos
  apt_key: url="{{ item }}"
  with_items:
    - https://dl-ssl.google.com/linux/linux_signing_key.pub
    - https://download.docker.com/linux/ubuntu/gpg


- name: setup repositries
  apt_repository: repo={{ item }} state=present
  with_items:
    - ppa:webupd8team/atom
    - deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    - ppa:notepadqq-team/notepadqq
    - deb http://dl.google.com/linux/chrome/deb/ stable main
    - ppa:videolan/stable-daily

- name: Download packages files
  get_url: url="{{ item.value.url }}" dest="{{ item.value.path }}" mode=0644
  with_dict: "{{ packages }}"


- name: install packages
  apt: deb="{{ item.value.path }}"
  when: " item.value.type  == 'deb'"
  with_dict: "{{ packages }}"

- name: unarchive intellij
  unarchive: dest=/opt src="{{ downloads_directory }}/ideaIC-2018.1.5.tar.gz" creates=/opt/intellij remote_src=yes

- name: install some packages
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=86400
  with_items:
    - atom
    - google-chrome-stable
    - vagrant
    - docker-ce
    - virtualbox
    - filezilla
    - notepadqq
    - openjdk-8-jdk
    - vlc
    - xpad
